# Generated by Django 5.0.14 on 2026-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255, unique=True)),
                ('name_translated', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('employee_count', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('normalized_key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Company group',
                'verbose_name_plural': 'Company groups',
                'db_table': 'company_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('vacancies_found', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('changed_count', models.IntegerField(default=0)),
                ('deactivated_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Scrape run',
                'verbose_name_plural': 'Scrape runs',
                'db_table': 'scrape_runs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('query', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Telegram subscription',
                'verbose_name_plural': 'Telegram subscriptions',
                'db_table': 'telegram_subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramSubscriptionDelivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Telegram delivery',
                'verbose_name_plural': 'Telegram deliveries',
                'db_table': 'telegram_subscription_deliveries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(blank=True, max_length=32, null=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(blank=True, null=True)),
                ('last_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
                'db_table': 'telegram_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('text_hash', models.CharField(max_length=64)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('translator', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Translation cache entry',
                'verbose_name_plural': 'Translation cache',
                'db_table': 'translation_cache',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('page_html', models.TextField(blank=True, null=True)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('salary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('salary_period', models.CharField(blank=True, max_length=20, null=True)),
                ('salary_type', models.CharField(blank=True, max_length=20, null=True)),
                ('welcome_ukraine', models.BooleanField(default=False)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'db_table': 'vacancies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField()),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vacancy change',
                'verbose_name_plural': 'Vacancy changes',
                'db_table': 'vacancy_changes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyTranslation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10)),
                ('title_translated', models.CharField(blank=True, max_length=500, null=True)),
                ('description_translated', models.TextField(blank=True, null=True)),
                ('translated_at', models.DateTimeField()),
                ('translator', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Vacancy translation',
                'verbose_name_plural': 'Vacancy translations',
                'db_table': 'vacancy_translations',
                'managed': False,
            },
        ),
    ]
